Add note command

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -7,7 +7,10 @@ set -e
 
 SCRIPTNAME=$(basename $0)
 
-# Return 0 if $2 contains all tags in $1 and 1 otherwise. Returns 0 in the 
+NOTE_F=$(dirname $TODO_F)/note
+NOTE_DONE_F=$(dirname $TODONE_F)/note-done
+
+# Return 0 if $2 contains all tags in $1 and 1 otherwise. Returns 0 in the
 # case that $1 is empty.
 match_tags() {
   WANTEDTAGS=$1
@@ -41,7 +44,7 @@ parse_linetags() {
   printf "%s" "$LINETAGS"
 }
 
-# If given a todo, then add that to the list of tasks. Otherwise, print all 
+# If given a todo, then add that to the list of tasks. Otherwise, print all
 # todo items which have the given tags
 do_todo() {
   [ -e "$TODO_F" ] || touch "$TODO_F"
@@ -53,6 +56,22 @@ do_todo() {
     done < "$TODO_F"
   else # Must be adding a new todo
     printf "TODO %s%s\n" "$INPUT" "${ARGTAGS:+ [$ARGTAGS]}" >> "$TODO_F"
+  fi
+  exit 0
+}
+
+# If given a todo, then add that to the list of tasks. Otherwise, print all
+# todo items which have the given tags
+do_note() {
+  [ -e "$NOTE_F" ] || touch "$NOTE_F"
+  if [ -z "$INPUT" ]; then # No todo given, so print current tasks with matching tags
+    while read -r LINE; do
+      if match_tags "$ARGTAGS" "$(parse_linetags "$LINE")"; then
+        output_line "$LINE"
+      fi
+    done < "$NOTE_F"
+  else # Must be adding a new todo
+    printf "TODO %s%s\n" "$INPUT" "${ARGTAGS:+ [$ARGTAGS]}" >> "$NOTE_F"
   fi
   exit 0
 }
@@ -94,8 +113,8 @@ do_todo_edit() {
   exit 0
 }
 
-# Enter an environment where all todo-* commands will already include the 
-# given tasks. Useful for focusing on a certain subset of tasks. This relies 
+# Enter an environment where all todo-* commands will already include the
+# given tasks. Useful for focusing on a certain subset of tasks. This relies
 # on bash, and is not portable
 do_todo_focus() {
   if [ -z "$ARGTAGS" ]; then
@@ -118,7 +137,7 @@ EOF
   rm $TMPFILE
 }
 
-# Mark any tasks matching the given pattern as done. Tags can also be 
+# Mark any tasks matching the given pattern as done. Tags can also be
 # specified to limit the scope of the match
 do_todone() {
   if [ -z "$INPUT" ]; then
@@ -149,7 +168,7 @@ do_todone() {
   mv "$TODO_F.tmp" "$TODO_F"
 }
 
-# Remove all DONE lines with the given tags from $TODO_F. All such lines will 
+# Remove all DONE lines with the given tags from $TODO_F. All such lines will
 # already have been added to $TODONE_F
 do_todone_archive() {
   > "$TODO_F.tmp"
@@ -165,7 +184,39 @@ do_todone_archive() {
   mv "$TODO_F.tmp" "$TODO_F"
 }
 
-# Show a formatted list of completed tasks (can be limited by specifying 
+# Mark any tasks matching the given pattern as done. Tags can also be
+# specified to limit the scope of the match
+do_note_rm() {
+  if [ -z "$INPUT" ]; then
+    printf "Error: no note to mark done specified\n" >&2
+    exit 1
+  fi
+
+  > "$NOTE_F.tmp"
+
+  HAD_MATCH=0
+  while read -r LINE; do
+    if [ "${LINE#TODO *$INPUT}" != "$LINE" ] && match_tags "$ARGTAGS" "$(parse_linetags "$LINE")"; then
+      HAD_MATCH=1
+      TASK="${LINE#TODO }"
+      LINE=$(printf "DONE %s ($(date "+%Y-%m-%d %R"))" "$TASK")
+      output_line "$LINE"
+      printf "%s\n" "$LINE" >> "$NOTE_DONE_F"
+    else
+      printf "%s\n" "$LINE" >> "$NOTE_F.tmp"
+    fi
+  done < "$NOTE_F"
+
+  if [ $HAD_MATCH -eq 0 ]; then
+    printf "Error: no tasks matched the given pattern\n" >&2
+    rm "$NOTE_F.tmp"
+    exit 1
+  fi
+
+  mv "$NOTE_F.tmp" "$NOTE_F"
+}
+
+# Show a formatted list of completed tasks (can be limited by specifying
 # desired tags).
 # This function uses tac which is non-POSIX, as is the -d argument to date
 do_todone_view() {
@@ -213,6 +264,10 @@ done
 
 if [ "$SCRIPTNAME" = "todo" ]; then
   do_todo
+elif [ "$SCRIPTNAME" = "note" ]; then
+  do_note
+elif [ "$SCRIPTNAME" = "note-rm" ]; then
+  do_note_rm
 elif [ "$SCRIPTNAME" = "todo-edit" ]; then
   do_todo_edit
 elif [ "$SCRIPTNAME" = "todo-focus" ]; then
